Gametag/config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :comments

  get "about" => "about#about"
  resources :homes do
    member do
      put "like" => "homes#vote"
    end
    resources :comments
  end
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Gametag/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Gametag/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :home
    belongs_to :user
end

Gametag/app/models/home.rb
class Home < ApplicationRecord
    acts_as_votable
    has_many :comments
    mount_uploader :imagem, PictureUploader
    belongs_to :user
end

Gametag/app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :homes
         has_many :comments
end

Gametag/app/controllers/about_controller.rb
class AboutController < ApplicationController
end

Gametag/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Gametag/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.home, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.home, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :home_id)
    end
end

Gametag/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, only: [:vote]
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :js, :json, :html

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @comments = @home.comments.all
    @comment = @home.comments.build
  end

  # GET /homes/new
  def new
    @home = current_user.homes.build
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = current_user.homes.build(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    if !current_user.liked? @home
      @home.liked_by current_user

    elsif current_user.liked? @home
      @home.unlike_by current_user
    end
    redirect_to @home
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:imagem, :descricao, :nome)
    end
end

Gametag/app/helpers/about_helper.rb
module AboutHelper
end

Gametag/app/helpers/application_helper.rb
module ApplicationHelper
end

Gametag/app/helpers/comments_helper.rb
module CommentsHelper
end

Gametag/app/helpers/homes_helper.rb
module HomesHelper
end

Gametag/app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">

    <div class="field">
      <br>
      <br>
      <%= form.label :Comentário %>
      <%= form.text_area :body, class:"form-control" %>
    </div>

    <%= form.hidden_field :home_id %>

    <div class="actions">
      <br>
      <%= form.submit 'Comentar',class:"btn btn-secondary"%>
    </div>
  </div>

<% end %>

Gametag/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

Gametag/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.home_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

Gametag/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

Gametag/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Home:</strong>
  <%= @comment.home_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

Gametag/app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <label>Imagem</label>
    <%= form.file_field :imagem, class:"form-control-file" %>
  </div>

  <div class="field">
    <label>Nome</label>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <div class="field">
    <label>Descrição</label>
    <%= form.text_area :descricao, class:"form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit 'Criar',class:"btn btn-secondary"%>
  </div>
</div>

<% end %>

Gametag/app/views/homes/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', home: @home %>

<div class="card-body">
  <%= link_to 'Back', homes_path, :class=>"btn btn-primary " %>
</div>

Gametag/app/views/homes/index.html.erb
<% if user_signed_in? %>
  <p id="notice"><%= notice %></p>

  <h1>Tags</h1>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Imagem</th>
        <th>Descrição</th>
        <th>Nome</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @homes.each do |home| %>
        <tr>
          <td><%= image_tag home.imagem_url, width: '150px' if home.imagem.present? %></td>
          <td><%= home.descricao %></td>
          <td><%= home.nome %></td>
          <td><%= link_to 'Show', home, :class=>"btn btn-primary" %></td>

          <% if home.user == current_user %>
            <td><%= link_to 'Edit', edit_home_path(home), :class=>"btn btn-secondary" %></td>
            <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-outline-danger" %></td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New tag', new_home_path, :class => "btn btn-primary btn-lg" %>


<%end%>

Gametag/app/views/homes/new.html.erb
<h1>New Tag</h1>

<%= render 'form', home: @home %>

<div class="card-body">
  <%= link_to 'Back', homes_path, :class=>"btn btn-primary " %>
</div>

Gametag/app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card text-white bg-dark mb-3" style="width: 70rem;">
  <h5 class="card-header"><%= @home.nome %></h5>
  <%= image_tag(@home.imagem_url, width: 150, class:"card-img-top") if @home.imagem.present? %>

  <div class="card-body">
    <p class="card-text"><%= @home.descricao %></p>
    <% if current_user == @home.user %>
    <%= link_to 'Edit', edit_home_path(@home), :class=>"btn btn-primary" %>
    <%end%>
    <%= link_to 'Back', homes_path, :class=>"btn btn-primary " %>
    <%= link_to like_home_path(@home), class:"like-btn", method: :put, remote: :true do%>
    <br>
    <br>
    <div class="btn btn-success">
      Like <span class="badge badge-light"><spam class="likes-count"><%= @home.get_upvotes.size %> </spam></span>
      <spam><p><i class= "fa fa-thumbs-up fa-3x"></i></p></spam>
    </div>
    <% end %>
  </div>
</div>

<br>
<h1>Comments</h1>
<br>

<% @comments.each do |comment| %>
  <div class="card text-white bg-dark mb-3" style="width: 70rem;">
    <h5 class="card-header"><%= comment.user.email %></h5>
    <div class="card-body">
      <p class="card-text"><%= comment.body %></p>
      <% if comment.user == current_user %>
        <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></p>
      <%end%>
    </div>
    <br>
  </div>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>

Gametag/app/views/homes/vote.js.erb
<% if current_user.liked? @home %>
    $('.like-btn').addClass('liked');

    <% else %>
        $('.like-btn').addClass('like-btn');
    <%end%>
    $('.likes-count').html("<%= @home.get_upvotes.size %>")

Gametag/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if user_signed_in? %>
     <% else %>
      <ul>
      <br>
      <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-primary"><%= link_to 'Sign up', new_user_registration_path,class:"btn btn-primary"%></button>
        <button type="button" class="btn btn-primary"><%= link_to 'Sign in', new_user_session_path, class:"btn btn-primary" %></button>
      </div>
      </ul>
     <% end %>
    <title>Gametag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/about">GameTag</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="/homes">Tags</a>
            </li>

            <% if user_signed_in?%>
              <li class="nav-item">
                <%= link_to 'Account', edit_user_registration_path, :class => "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class => "nav-link"%>
              </li>
            <%end%>

          </ul>
        </div>
      </nav>
    <%end%>
  	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	  <% end %>
	  <% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	  <% end %>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>